trigger:
  - main  # Trigger pipeline on push to 'main' branch

pool:
  name: "Self_Hosted"  # Use a Microsoft-hosted agent

steps:
  - checkout: self

  - task: UseNode@1
    inputs:
      version: '20.18.0'  # Set to your Node.js version

  - script: ls -la
    displayName: 'List files in workspace'

  - script: npm install
    displayName: 'Install dependencies in root directory'

  - script: npm run build
    displayName: 'Build application'

  - script: npm test
    displayName: 'Run tests'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '.'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'AzureWebAppConnection'
      appName: 'XRWebsites-frontend-test'
      package: '$(Build.ArtifactStagingDirectory)/app.zip'
      deploymentMethod: 'runFromPackage'
