trigger:
  branches:
    include:
      - main
  paths:
    include:
      - azure_pipelines/azure-pipelines.yml
      - frontend/**

variables:
  azureSubscription: "9abd54ba-7abf-43d5-b936-973310267f7d"
  webAppName: "xrwebsites-frontend"
  environmentName: "xrwebsites-frontend"
  agentPoolName: "Self_Hosted"  # Self-hosted agent pool
  agentName: "Lamont"           # Specific agent name
  frontendDir: "frontend"
  distDir: "$(frontendDir)/dist"

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          name: $(agentPoolName)  # Use self-hosted pool
          demands:
            - Agent.Name -equals $(agentName)  # Use specific agent "Lamont"
        timeoutInMinutes: 180  # ⏳ Increased timeout from 60 to 120 minutes

        steps:
          - checkout: self

          - task: NodeTool@0
            inputs:
              versionSpec: "20.18.0"
            displayName: "Install Node.js"

          - script: |
              cd $(frontendDir)
              npm ci
              npm run build
            displayName: "Install Dependencies and Build"

          - script: |
              cd $(frontendDir)
              cp package.json dist/
              cp server.js dist/
              cd dist
              npm install --production
              echo '#!/bin/bash' > run.sh
              echo 'npm run start' >> run.sh
              chmod +x run.sh
            displayName: "Setup Deployment"

          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: "$(distDir)"
              artifactName: "frontend-dist"
            displayName: "Publish Build Artifacts"

  - stage: Deploy
    displayName: Deploy stage
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: $(environmentName)
        pool:
          vmImage: $(vmImageName)
        timeoutInMinutes: 180  # ⏳ Increased timeout for deployment
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  displayName: "Azure App Service Deploy: xrwebsites-frontend"
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appType: webAppLinux
                    WebAppName: $(webAppName)
                    packageForLinux: "$(Pipeline.Workspace)/frontend-dist"
                    RuntimeStack: "NODE|20LTS"
                    StartupCommand: "bash run.sh"
