trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "frontend/**"

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseNode@1
    inputs:
      version: "20.18.0"

  - script: |
      cd frontend
      npm ci
      npm run build
    displayName: "Install dependencies and build"

  - script: |
      cd frontend
      cp package.json dist/
      cp server.js dist/
      cd dist
      npm install --production
      echo '#!/bin/bash' > run.sh
      echo 'npm run start' >> run.sh
      chmod +x run.sh
    displayName: "Setup deployment files"

  - task: AzureWebApp@1
    inputs:
      azureSubscription: "AzureServiceConnection"  # Replace with your Azure service connection name
      appName: "xrwebsites-frontend"
      deployToSlotOrASE: true
      resourceGroupName: "xrwebsites-rg"  # Replace with your resource group
      slotName: "Production"
      package: "frontend/dist"
      publishProfile: "$(XRWEBSITES_FRONTEND_PUBLISH_PROFILE)"  # Use the variable instead of a secure file
    displayName: "Deploy to Azure Web App"
