name: Deploy Frontend to Azure

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.18.0"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies and build
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Setup deployment
        run: |
          cd frontend
          cp package.json dist/
          cp server.js dist/
          cd dist
          echo '#!/bin/bash' > run.sh
          echo 'npm install' >> run.sh
          echo 'npm run start' >> run.sh
          chmod +x run.sh

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "xrwebsites-frontend"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FRONTEND }}
          package: frontend/dist
