trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "frontend/**"

pool:
  name: "Self_Hosted"

steps:
  - task: UseNode@1
    inputs:
      version: "20.18.0"  # Ensure Node.js version is correct for your project

  - script: |
      cd frontend
      npm ci
      npm run build
    displayName: "Install dependencies and build"

  - script: |
      cd frontend
      cp package.json dist/
      cp server.js dist/
      cd dist
      npm install --production
      echo '#!/bin/bash' > run.sh
      echo 'npm run start' >> run.sh
      chmod +x run.sh
    displayName: "Setup deployment files"

  - task: AzureWebApp@1
    inputs:
      azureSubscription: "AzureServiceConnection"  # Ensure this matches your service connection name
      appName: "xrwebsites-frontend"  # Ensure this matches your app name in Azure
      deployToSlotOrASE: true  # Set this to true if you're using a slot for deployment
      resourceGroupName: "xrwebsites-rg"  # Ensure this matches your resource group name
      slotName: "Production"  # Set this to your slot name if using slots in Azure
      package: "frontend/dist"  # Path to the build folder
      publishProfile: "$(XRWEBSITES_FRONTEND_PUBLISH_PROFILE)"  # Make sure this variable is defined and contains the correct publish profile
    displayName: "Deploy to Azure Web App"
