trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "frontend/**"

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseNode@1
    inputs:
      version: "20.18.0"

  - script: |
      cd frontend
      npm ci
      npm run build
    displayName: "Install dependencies and build"

  - script: |
      cd frontend
      cp package.json dist/
      cp server.js dist/
      cd dist
      npm install --production
      echo '#!/bin/bash' > run.sh
      echo 'npm run start' >> run.sh
      chmod +x run.sh
    displayName: "Setup deployment files"

  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'xrwebsites-frontend.PublishSettings'
    displayName: "Download Secure Publish Profile"

  - task: AzureWebApp@1
    inputs:
      azureSubscription: "AzureServiceConnection" # Replace with your Azure service connection
      appName: "xrwebsites-frontend"
      deployToSlotOrASE: true
      resourceGroupName: "xrwebsites-rg" # Replace with your resource group
      slotName: "Production"
      package: "frontend/dist"
    displayName: "Deploy to Azure Web App"
