name: Deploy Frontend to Azure

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.18.0"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies and build
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Setup deployment
        run: |
          cd frontend/dist
          npm install -g serve
          echo '#!/bin/bash' > run.sh
          echo 'cd /home/site/wwwroot' >> run.sh
          echo '/usr/local/bin/serve -s . -l 8080' >> run.sh
          chmod +x run.sh
          cp ../web.config .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "xrwebsites-frontend"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FRONTEND }}
          package: frontend/dist
